### ISSUE TITLE
Today Todo

### ISSUE THREAD

**Issue by laurensWe** [matsmulder/MinorProject#18]
- [x] Stopping criteria
- [x] implementing UI
- [ ] Analytics
- [ ] Stats menu after game finished
- [ ] build world with extra environmental meshes
- [ ] *optionally implementing animations

**Comment by laurensWe** [comment]
DONE: UI, analytics, world builded.
TODO: stop criteria, stats, animations

**Comment by laurensWe** [comment]
DONE: stop criteria
